tags:
- name: products
  description: products API

paths:
# [GET] products/all
  /products/all:
    get:
      tags:
      - products
      summary: Find All Products
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'
          
# [GET] products
  /products:
    get:
      tags:
      - products
      summary: Get Products
      parameters:
      - name: limit
        description: Limit
        required: false
      - name: offset
        description: Offset
        required: false
      responses:
        200:
          description: 'OK'
        416: 'Range Not Satisfiable'
        500:
          description: 'Server Error'

# [GET] products/id
  /products/{id}:
    get:
      tags:
      - products
      summary: Find Product By Id
      parameters:
      - name: id
        in: path
        description: Product Id
        required: true
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

schemes:
 - https
 - http
